change testping to take in file as arg, remove '-t 1' option from ping

diff --git a/testping b/testping
--- a/testping
+++ b/testping
@@ -3,15 +3,18 @@ red=`tput setaf 1`
 green=`tput setaf 2`
 reset=`tput sgr0`
 
+file=$1
+
 #loop through first words of each line
-for computer in $(cut -d ':' -f1 dummyFile); do
-	ping -c 1 -t 1 $computer > /dev/null
-	result=$?
-	status=""
-	if [ $result = "0" ]; then
-		status="${green}online ${reset}"
-	else
-		status="${red}offline ${reset}"
-	fi
-	echo -e "$computer: $status"	
+for computer in $(cut -d ':' -f1 $file); do
+  #ping -c 1 only does 1 packet, only care about exit status not output
+  ping -c 1 $computer > /dev/null
+  result=$?
+  status=""
+  if [ $result = "0" ]; then
+    status="${green}online ${reset}"
+  else
+    status="${red}offline ${reset}"
+  fi
+  echo -e "$computer: $status"	
 done
